// rAthena msg_athena.conf
// Message Configuration of Custom
// -----------------------

// Craft System Messages
3000: [Craft] You have entered the shop
3001: [Craft] You can craft multiple items at once
3002: ================ [ Craft System ] ================
3003: > - %s ~ %0.2f%% [%d Zeny]
3004: > - %s ~ %0.2f%% [%d Zeny] %s
3005: ===========================================
3006: [Craft System] You cannot craft more than one type at a time
3007: [Craft System] %s crafted %s x%d - Success: %d Failed: %d
