// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),

// Enchantgrade random-option helpers
// Author: V!be Coding [kreanlnwza] AI Assistant (Antigravity)
ACMD_DEF(gradedown),
ACMD_DEF(addopt5),
ACMD_DEF(rerollopt),
