// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Map Flags
 * Place custom MF_ entries in this file.
 * They will be added before MF_MAX in the e_mapflag enum.
 * Format:
 *	MF_YOURFLAG,
 *
 * Remember to also add the corresponding export_constant()
 * in custom/script_constants_custom.inc
 *
 * Author: V!be Coding [kreanlnwza] AI Assistant (Claude)
 **/

//MF_EXAMPLE,
MF_DROPRATE,
