// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

// Gachapong System - Random item by type
// Author: V!be Coding [kreanlnwza] AI Assistant (Claude)
BUILDIN_DEF(gachapong_rand,"i?"),
BUILDIN_DEF(gachapong_count,"i"),
BUILDIN_DEF(gachapong_build,""),
BUILDIN_DEF(gachapong_rand_equip,"i?"),
BUILDIN_DEF(gachapong_count_equip,"i"),
