// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Constants
 * Place custom export_constant() entries for MF_, SC_, and EFST_ here.
 * Format:
 *	export_constant(MF_YOURFLAG);
 *	export_constant(SC_YOURSTATUS);
 *	export_constant(EFST_YOUREFFECT);
 *
 * Author: V!be Coding [kreanlnwza] AI Assistant (Claude)
 **/

/* Custom Map Flags */
//export_constant(MF_EXAMPLE);
export_constant(MF_SUMMONER);
export_constant(MF_DROPRATE);

/* Custom Status Changes */
//export_constant(SC_EXAMPLE);

/* Custom Effect Statuses */
//export_constant(EFST_EXAMPLE);
