// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Effect Statuses (EFST)
 * Place custom EFST_ entries in this file.
 * They will be added before EFST_MAX in the efst_type enum.
 * Format:
 *	EFST_YOUREFFECT,
 *
 * Remember to also add the corresponding export_constant()
 * in custom/script_constants_custom.inc
 *
 * Author: V!be Coding [kreanlnwza] AI Assistant (Claude)
 **/

//EFST_EXAMPLE,
EFST_WEIGHT_SPEED_PENALTY,
