//--------------------------------------------------------------
// Rodex
//--------------------------------------------------------------

// Whether or not mail box status is displayed upon login.
// Default: 0
// 0 = No
// 1 = Yes
// 2 = Yes, when there are unread mails
mail_show_status: 0

// Amount of mails a user can send a day.
// Default: 100
// 0 = Unlimited
mail_daily_count: 100

// Fee for transferring zeny via mail (Note 2)
// NOTE: this rate is hardcoded in the client, you need to diff your client accordingly if you change this value.
// Default: 20(20%)
// 0 = No fee
mail_zeny_fee: 20

// Amount of zeny to pay for each attached item
// NOTE: this fee is hardcoded in the client, you need to diff your client accordingly if you change this value.
// Default: 2500
// 0 = No fee
mail_attachment_price: 2500

// Maximum weight in total that can be attached to a mail
// NOTE: this limit is hardcoded in the client, you need to diff your client accordingly if you change this value.
// Default: 2000
// 0 = No weight limit
mail_attachment_weight: 2000

//--------------------------------------------------------------
// Trade
//--------------------------------------------------------------
// Fee for transferring zeny via trade (Note 2)
// Default: 20(20%)
// 0 = No fee
trade_zeny_fee: 20

// Amount of zeny to pay for transferring item via trade
// Default: 1000
// 0 = No fee
tradeitem_fee: 1000

// Amount of zeny to pay for transferring item Refine/Enchant Grade via trade
// Default: 2500
// 0 = No fee
trade_refine_fee: 2000
trade_enchantgrade_fee: 2500

//--------------------------------------------------------------
// Sell to NPC
//--------------------------------------------------------------
// Tax rate when selling items to NPC (Note 2)
// The sell price will be reduced by this percentage
// Default: 30(30%)
// 0 = No tax
sell_zeny_fee: 30